#!/usr/bin/env python3
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import rospy 
from fusion_control_lib.pick_action_srv import PickActionNode
from fusion_control_lib.place_action_srv import PlaceActionNode
from fusion_control_lib.give_action_srv import GiveActionNode
from fusion_control_lib.move_action_srv import MoveActionNode

def control_main(args=None):

    print("Pick action node")
    rospy.init_node('pick_action_node', anonymous=True)

    pick_server = PickActionNode("pick_action_server") 
    place_server = PlaceActionNode("place_action_server")
    give_server = GiveActionNode("give_action_server")
    move_server = MoveActionNode("move_action_server")
    pick_server.start_node()
    place_server.start_node()
    give_server.start_node()
    move_server.start_node()
    rospy.spin()
    
if __name__ == "__main__":
    control_main()


