#!/usr/bin/env python3
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import rospy 
from task_director_submodules import TaskDirector
JSON_PATH = "/home/alex/user_files/nqnosa/ROBO-666/corob_2024/ros1env/src/json_files/"
DETECTIONS_FILE_PATH = JSON_PATH + 'detections.json'
FAULT_FILE_PATH = JSON_PATH + 'fault_detections.json'
TASKS_FILE_PATH = JSON_PATH + 'tasks.json'
TOOL_FILE_PATH = JSON_PATH + 'tools.json'

def task_server_main(args=None):

    rospy.init_node('task_director', anonymous=True)
    task_director_node = TaskDirector(DETECTIONS_FILE_PATH, 
                                      FAULT_FILE_PATH,
                                      TASKS_FILE_PATH)
    rospy.spin() 

if __name__ == "__main__":
    task_server_main()


