#!/usr/bin/env python3
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import rospy 
from chatter_submodules import FeedbackTalker
from chatter_submodules.json_utils import read_json_file, id_to_name_dict

# Replace with your path to .json files 
JSON_PATH = "/root/ROBO-666/corob_2024/src/json_files/"
COMMANDS_PATH = JSON_PATH + "commands.json"
TARGETS_PATH = JSON_PATH + "targets.json"
TOOLS_PATH = JSON_PATH + "tools.json"
TASKS_PATH = JSON_PATH + "tasks.json"


def talker_main(args=None):
    
    rospy.init_node('feedback_server', anonymous=True)

    commands = read_json_file(COMMANDS_PATH, "commands")
    targets = read_json_file(TARGETS_PATH, "targets")
    objects = id_to_name_dict(targets, 'object')
    directions = id_to_name_dict(targets, 'direction')
    locations = id_to_name_dict(targets, 'location')
    tasks = read_json_file(TASKS_PATH, "tasks")
    tools = read_json_file(TOOLS_PATH, "tools")

    FeedbackTalker(commands, objects, directions, locations, tasks, tools)
    rospy.loginfo("Feedback server started.")
    rospy.spin()

if __name__ == "__main__":
    talker_main()


